-- SCRIPT FINAL DE RESET E CONFIGURAÇÃO (LOJA NATURAL)
-- Este script apaga tudo o que foi feito antes e recria o banco de dados do zero de forma limpa.

-- 1. LIMPEZA TOTAL (RESET)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 2. TABELA DE PERFIS (PROFILES)
-- Armazena se o usuário é administrador ou não.
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email text NOT NULL,
  is_admin boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativar segurança (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso
CREATE POLICY "Perfis são visíveis para todos" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Usuários inserem seu próprio perfil" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Usuários atualizam seu próprio perfil" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 3. AUTOMAÇÃO DE CADASTRO (TRIGGER)
-- Cria automaticamente um perfil quando um novo e-mail é cadastrado.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, is_admin)
  VALUES (new.id, new.email, false);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 4. TABELA DE PRODUTOS (PRODUCTS)
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  fullDescription text,
  price decimal NOT NULL,
  image text,
  category text,
  benefits text[],
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Políticas para produtos
CREATE POLICY "Produtos visíveis para todos" ON public.products FOR SELECT USING (true);
CREATE POLICY "Admins inserem produtos" ON public.products FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true)
);
CREATE POLICY "Admins atualizam produtos" ON public.products FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true)
);
CREATE POLICY "Admins deletam produtos" ON public.products FOR DELETE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true)
);

-- 5. STORAGE (CONFIGURAÇÃO MANUAL)
-- ATENÇÃO: Você deve criar manualmente um bucket chamado 'products' no Supabase Storage e deixá-lo como 'Public'.
