-- 1. PROFILES TABLE
-- Create a table for public profiles
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  is_admin boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, is_admin)
  values (new.id, new.email, false);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. PRODUCTS TABLE
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  fullDescription text,
  price decimal not null,
  image text,
  category text,
  benefits text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table products enable row level security;

-- Policies
create policy "Products are viewable by everyone." on products
  for select using (true);

create policy "Admins can insert products." on products
  for insert with check (
    exists (
      select 1 from profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can update products." on products
  for update using (
    exists (
      select 1 from profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can delete products." on products
  for delete using (
    exists (
      select 1 from profiles
      where id = auth.uid() and is_admin = true
    )
  );


-- 3. STORAGE SETUP
-- You should manually create a public bucket named 'products' in Supabase Storage.
-- Then add these policies for the 'products' bucket:
-- Select: All users
-- Insert/Update/Delete: Authenticated users (with is_admin check)
