import React, { createContext, useContext, useEffect, useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import { products as initialProducts } from '../data/products';

const ProductContext = createContext({});

export const ProductProvider = ({ children }) => {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchProducts = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('products')
        .select('*')
        .order('id', { ascending: true });

      if (error) {
        console.error('Error fetching products from Supabase:', error);
        setProducts(initialProducts);
      } else {
        // If data is empty array, also fallback to initialProducts for the first run
        setProducts(data && data.length > 0 ? data : initialProducts);
      }
    } catch (err) {
      console.error('Fetch products error:', err);
      setProducts(initialProducts);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchProducts();
  }, []);

  const addProduct = async (productData, imageFile) => {
    let imageUrl = productData.image;

    // Handle image upload if a file is provided
    if (imageFile) {
      const fileExt = imageFile.name.split('.').pop();
      const fileName = `${Math.random()}.${fileExt}`;
      const filePath = `product-images/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from('products')
        .upload(filePath, imageFile);

      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage
        .from('products')
        .getPublicUrl(filePath);
      
      imageUrl = publicUrl;
    }

    const { data, error } = await supabase
      .from('products')
      .insert([{ ...productData, image: imageUrl }])
      .select();

    if (error) throw error;
    setProducts([...products, data[0]]);
    return data[0];
  };

  const updateProduct = async (id, updates, imageFile) => {
    let imageUrl = updates.image;

    if (imageFile) {
      const fileExt = imageFile.name.split('.').pop();
      const fileName = `${Math.random()}.${fileExt}`;
      const filePath = `product-images/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from('products')
        .upload(filePath, imageFile);

      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage
        .from('products')
        .getPublicUrl(filePath);
      
      imageUrl = publicUrl;
    }

    const { data, error } = await supabase
      .from('products')
      .update({ ...updates, image: imageUrl })
      .eq('id', id)
      .select();

    if (error) throw error;
    setProducts(products.map(p => p.id === id ? data[0] : p));
    return data[0];
  };

  const deleteProduct = async (id) => {
    const { error } = await supabase
      .from('products')
      .delete()
      .eq('id', id);

    if (error) throw error;
    setProducts(products.filter(p => p.id !== id));
  };

  return (
    <ProductContext.Provider value={{ products, loading, addProduct, updateProduct, deleteProduct, refreshProducts: fetchProducts }}>
      {children}
    </ProductContext.Provider>
  );
};

export const useProducts = () => useContext(ProductContext);

/*
SQL SETUP FOR PRODUCTS TABLE:

create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  fullDescription text,
  price decimal not null,
  image text,
  category text,
  benefits text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table products enable row level security;

-- Policies
create policy "Products are viewable by everyone." on products
  for select using (true);

create policy "Admins can insert products." on products
  for insert with check (
    exists (
      select 1 from profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can update products." on products
  for update using (
    exists (
      select 1 from profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins can delete products." on products
  for delete using (
    exists (
      select 1 from profiles
      where id = auth.uid() and is_admin = true
    )
  );

-- Storage bucket setup:
-- 1. Create a bucket named "products" and make it public.
-- 2. Add policies for the "products" bucket:
--    - "Public Access": Select for all
--    - "Admin Upload": Insert/Update for auth.uid() if is_admin
*/
